<?php
declare (strict_types=1);

namespace App\Services\Repositories\Manage\Providers;


use App\Services\Repositories\Manage\Interfaces\ILog;
use App\Services\Repositories\Manage\Interfaces\IManage;
use App\Services\Repositories\Manage\LogRepo;
use App\Services\Repositories\Manage\ManageRepo;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * 管理相关模块服务注册
 * Class RepositoryServiceProvider
 * @package App\Services\Repositories\Manage\Providers
 */
class RepositoryServiceProvider extends ServiceProvider
{

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        $this->app->bind(IManage::class, ManageRepo::class);
        $this->app->bind(ILog::class, LogRepo::class);

    }

}
