<?php


namespace App\Providers;


use App\Services\Captcha\Image\Captcha;
use App\Services\Contracts\Captcha as CaptchaContract;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * 注册服务
 * Class RepositoryServiceProvider
 * @package App\Providers
 */
class RepositoryServiceProvider extends ServiceProvider
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * 注册服务
     */
    public function register()
    {
        //平台管理员
        if (class_exists(\App\Services\Repositories\Manage\Providers\RepositoryServiceProvider::class)) {
            $this->app->register(\App\Services\Repositories\Manage\Providers\RepositoryServiceProvider::class);
        }
        /**
         * 绑定图形验证码
         */
        $this->app->bind(CaptchaContract::class, function () {
            $captcha = new Captcha();
            $config = collect(config('laraveladmin.captcha'))->filter(function ($value) {
                return !empty($value);
            })->toArray();
            $captcha->withConfig($config);
            return $captcha;
        });
    }
}
