const enumInfo = {
    NATION_ENUM: [
        { value: 1001, label: '汉族' },
        { value: 1002, label: '蒙古族' },
        { value: 1003, label: '回族' },
        { value: 1004, label: '藏族' },
        { value: 1005, label: '维吾尔族' },
        { value: 1006, label: '苗族' },
        { value: 1007, label: '彝族' },
        { value: 1008, label: '壮族' },
        { value: 1009, label: '布依族' },
        { value: 1010, label: '朝鲜族' },
        { value: 1011, label: '满族' },
        { value: 1012, label: '侗族' },
        { value: 1013, label: '瑶族' },
        { value: 1014, label: '白族' },
        { value: 1015, label: '土家族' },
        { value: 1016, label: '哈尼族' },
        { value: 1017, label: '哈萨克族' },
        { value: 1018, label: '傣族' },
        { value: 1019, label: '黎族' },
        { value: 1020, label: '傈傈族' },
        { value: 1021, label: '佤族' },
        { value: 1022, label: '畲族' },
        { value: 1023, label: '高山族' },
        { value: 1024, label: '拉祜族' },
        { value: 1025, label: '水族' },
        { value: 1026, label: '东乡族' },
        { value: 1027, label: '纳西族' },
        { value: 1028, label: '景颇族' },
        { value: 1029, label: '柯尔克孜族' },
        { value: 1030, label: '土族' },
        { value: 1031, label: '达翰尔族' },
        { value: 1032, label: '仫佬族' },
        { value: 1033, label: '羌族' },
        { value: 1034, label: '布朗族' },
        { value: 1035, label: '撒拉族' },
        { value: 1036, label: '毛南族' },
        { value: 1037, label: '仡佬族' },
        { value: 1038, label: '锡伯族' },
        { value: 1039, label: '阿昌族' },
        { value: 1040, label: '普米族' },
        { value: 1041, label: '塔吉克族' },
        { value: 1042, label: '怒族' },
        { value: 1043, label: '乌孜别克族' },
        { value: 1044, label: '俄罗斯族' },
        { value: 1045, label: '鄂温克族' },
        { value: 1046, label: '德昂族' },
        { value: 1047, label: '保安族' },
        { value: 1048, label: '裕固族' },
        { value: 1049, label: '京族' },
        { value: 1050, label: '塔塔尔族' },
        { value: 1051, label: '独龙族' },
        { value: 1052, label: '鄂伦春族' },
        { value: 1053, label: '赫哲族' },
        { value: 1054, label: '门巴族' },
        { value: 1055, label: '珞巴族' },
        { value: 1056, label: '基诺族' },
        { value: 1090, label: '外籍人士' },
        { value: 1091, label: '其他族' },
        { value: 1092, label: '外国血统' },
        { value: 1098, label: '外国民族' },
    ],
    EDUCATION_ENUM: [
        { value: 101, label: '专科' },
        { value: 102, label: '本科' },
        { value: 103, label: '硕士在读' },
        { value: 104, label: '硕士' },
        { value: 105, label: '博士在读' },
        { value: 106, label: '博士' },
        { value: 199, label: '其他' }
    ],
    POLITICAL_STATUS_ENUM: [
        { value: 101, label: '中共党员' },
        { value: 102, label: '中共预备党员' },
        { value: 103, label: '共青团员' },
        { value: 112, label: '无党派人士/民族党派' },
        { value: 113, label: '群众' },
        { value: 114, label: '其他' }
    ],
    GENDER_ENUM: [
        { value: 1, label: '男' },
        { value: 2, label: '女' },
        { value: 0, label: '未知' },
    ],
    MARRY_ENUM: [
        { value: 0, label: '未婚' },
        { value: 1, label: '已婚' }
    ],
}
export default enumInfo